services:
  - type: web
    name: glowi
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_NAME
        value: glowi
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        value: your-db-pass
